import type { SiteConfig } from '../site-config'

export const automoveisConfig: SiteConfig = {
    name: 'Automóveis',
    description: 'Notícias, comparativos e dicas sobre carros, veículos elétricos, manutenção e mobilidade urbana. Encontre reviews atualizados, informações sobre seguros e infraestrutura de recarga.',
    domain: 'automoveis.neostream.com.br', // TODO: Substitua pelo seu domínio
    url: 'https://automoveis.neostream.com.br', // TODO: Substitua pela sua URL
    logo: '/logo.png',
    favicon: '/favicon.ico',
    adsenseId: 'ca-pub-6189411019780384', // TODO: Substitua pelo seu ID do AdSense
    themeColor: '#3b82f6', // blue-500
    defaultLocale: 'pt-BR',
    author: {
        name: 'Rafael Montenegro',
        email: 'rafael@neostream.com.br',
        url: 'https://automoveis.neostream.com.br/sobre',
        bio: 'Rafael cresceu desmontando motores e hoje percorre o mundo testando os últimos lançamentos das montadoras. Apaixonado por carros elétricos e mobilidade urbana, traz análises técnicas com linguagem acessível.',
        credentials: 'Engenheiro Automotivo e Testador Profissional | São Paulo, Brasil',
        image: '/autor.png'
    },
    social: {
        twitter: '@automoveis', // TODO: Substitua pelo seu Twitter
        github: 'username/automoveis', // TODO: Substitua pelo seu GitHub
        linkedin: 'company/automoveis' // TODO: Substitua pelo seu LinkedIn
    },
    seo: {
        defaultTitle: 'Automóveis',
        titleTemplate: '%s | Automóveis',
        defaultDescription: 'Notícias, comparativos e dicas sobre carros, veículos elétricos, manutenção e mobilidade urbana. Encontre reviews atualizados, informações sobre seguros e infraestrutura de recarga.',
        keywords: [
            "compra de carros usados",
            "carros seminovos baratos",
            "venda de veículos online",
            "tabela fipe atualizada",
            "melhor hora para comprar carro",
            "negociação preço carro",
            "avaliação carros usados",
            "documentação transferência veicular",
            "consórcio automóvel 2025",
            "trocar de carro dicas",
            "kilometragem ideal seminovos",
            "financiamento sem entrada",
            "garantia carros usados",
            "test drive grátis",
            "feirão de carros online",
            "carros mais vendidos 2025",
            "webmotors ofertas",
            "anúncio de carros grátis",
            "certificado de procedência",
            "laudo cautelar veículo",
            "volkswagen gol 2025",
            "chevrolet onix consumo",
            "fiat strada 1.3",
            "ford ka manutenção",
            "toyota corolla híbrido",
            "hyundai hb20 preço",
            "renault kwid elétrico",
            "fiat uno 1.0",
            "chevrolet celta peças",
            "jeep compass diesel",
            "nissan kicks 2025",
            "honda civic touring",
            "volkswagen polo gts",
            "fiat pulse turbo",
            "peugeot 208 griffe",
            "citroen c3 novo",
            "chevrolet tracker 2025",
            "hyundai creta safety",
            "volkswagen t-cross preço",
            "fiat argo drive",
            "carro elétrico barato",
            "autonomia carro elétrico",
            "pontos de recarga brasil",
            "carros híbridos 2025",
            "byd dolphin ficha técnica",
            "tesla model 3 brasil",
            "bmw ix1 preço",
            "renault kwid e-tech",
            "manutenção veículos elétricos",
            "carros elétricos usados",
            "carros elétricos isenção ipi",
            "incentivos fiscais evs",
            "bateria lfp vantagens",
            "tempo de recarga rápida",
            "wallbox instalação preço",
            "car sharing elétrico",
            "suv elétrico compacto",
            "carros híbridos flex",
            "taxa financiamento ev",
            "seguro carro elétrico",
            "troca de óleo preço",
            "alinhamento e balanceamento",
            "freio rangendo solução",
            "quando trocar pneus",
            "limpeza sistema arrefecimento",
            "correia dentada quilometragem",
            "vela de ignição sintomas",
            "diagnóstico eletrônico automotivo",
            "suspensão barulho",
            "calibragem pneu tabela",
            "ar condicionado automotivo",
            "bateria descarregando rápido",
            "câmbio automático revisão",
            "palhetas limpador silicone",
            "fluido de freio dot4",
            "embreagem patinando",
            "check up preventivo",
            "oficina especializada híbrido",
            "revisão 60 mil km",
            "custo manutenção corolla",
            "pneu 195 55 r15",
            "rodas liga leve aro 17",
            "filtro de ar esportivo",
            "multimídia android auto",
            "lâmpada led h7",
            "tapete automotivo borracha",
            "câmera de ré wireless",
            "alarme automotivo 2025",
            "sensor de estacionamento",
            "racks de teto universais",
            "engate reboque legalizado",
            "farol de milha neblina",
            "retrovisor elétrico universal",
            "carregador usb veicular",
            "película insulfilm g5",
            "som automotivo potente",
            "barra estabilizadora esportiva",
            "capa protetora carro",
            "kit xenon legal",
            "calha de chuva slim",
            "seguro auto barato",
            "cotação seguro online",
            "franquia reduzida vantagens",
            "classe de bônus seguradora",
            "assistência 24h carro",
            "rastreador veicular seguro",
            "financiamento taxa zero",
            "simulação financiamento banco",
            "score para financiamento",
            "leasing de carro no brasil",
            "consórcio ou financiamento",
            "taxas juros cdc auto",
            "refinanciamento de veículo",
            "seguro para carro híbrido",
            "cobertura danos naturais",
            "vistoria prévia obrigatória",
            "pequena monta seguro",
            "proteção contra roubo",
            "quitar financiamento antes",
            "seguro carro seminovo",
            "chip de potência",
            "remap motor turbo",
            "escape esportivo legalizado",
            "downpipe vantagens",
            "suspensão a ar preço",
            "roda maior consumo",
            "cold air intake",
            "intercooler dimensionamento",
            "aerofólio funcional",
            "pneu semi-slick rua",
            "embreagem cerâmica",
            "banco concha homologado",
            "freio brembo upgrade",
            "roll cage segurança",
            "stage 2 requisitos",
            "alinhamento caster camber",
            "datalogger obd2",
            "vela iridium troca",
            "acelerador eletrônico delay",
            "mapa flexpower",
            "dirigir na chuva",
            "economia de combustível dicas",
            "acelerar em rodovia",
            "troca de marcha ideal",
            "condução defensiva",
            "hidratar borrachas portas",
            "reduzir consumo ar condicionado",
            "pressão pneu economia",
            "peso extra porta-malas",
            "uso correto cruise control",
            "lavagem a seco carro",
            "polimento farol caseiro",
            "higienização interna",
            "dirigir na serra",
            "ponto cego espelho",
            "uso correto start stop",
            "parar em descida segura",
            "carro parado estraga?",
            "rodízio de pneus",
            "etanol ou gasolina",
            "ipva 2025 isenção",
            "licenciamento digital",
            "multas gravíssimas valores",
            "rodízio veicular sp",
            "renavam consulta grátis",
            "transferência digital veicular",
            "inspeção veicular obrigatória",
            "cnh digital app",
            "teto para pontos cnh",
            "placa mercosul requisitos",
            "decalque chassi vistoria",
            "tapete capacho proibido",
            "carro rebaixado lei",
            "led e xenon legislação",
            "insulfilm permitido",
            "adesivo envelopamento registro",
            "carro pcd regras",
            "medidor ruído escapamento",
            "dtc documento de trânsito",
            "recall obrigatório consulta",
            "lançamentos carros 2026",
            "carro autônomo nível 3",
            "tecnologia adas avançada",
            "5g nos veículos",
            "car sharing brasil 2025",
            "combustível sintético e-fuel",
            "hidrogênio na mobilidade",
            "fabricantes saas automotivo",
            "recall em massa airbags",
            "futuro dos hatch compactos",
            "marcas chinesas no brasil",
            "ritmo da eletrificação",
            "projeção vendas 2025",
            "carros mais vendidos ranking",
            "frota envelhecida efeito",
            "subsídio baterias brasil",
            "suv compacto tendência",
            "movimento downsizing motor",
            "marketplace peças online",
            "novos padrões euro 7"
        ]
    },
    legal: {
        privacyPolicyUrl: '/politica-de-privacidade',
        termsOfServiceUrl: '/termos-de-uso',
        cookiePolicyUrl: '/politica-de-cookies',
        aboutUrl: '/sobre'
    }
}