import type { SiteConfig } from '../site-config'

export const entretenimentoConfig: SiteConfig = {
    name: 'Entretenimento',
    description: 'Filmes, séries, livros, música e cultura pop - seu portal de entretenimento completo',
    domain: 'entretenimento.neostream.com.br',
    url: 'https://entretenimento.neostream.com.br',
    logo: '/logo.png',
    favicon: '/favicon.ico',
    adsenseId: 'ca-pub-6189411019780384',
    themeColor: '#a855f7',
    defaultLocale: 'pt-BR',
    author: {
        name: 'Zoë Carter',
        email: 'zoe@neostream.com.br',
        url: 'https://entretenimento.neostream.com.br/sobre',
        bio: 'Zoë é uma premiada roteirista e crítica de cinema com passagens pela Variety e IndieWire. Negra e feminista, sua escrita aborda o impacto social da cultura pop, diversidade e tendências do audiovisual.',
        credentials: 'Crítica Cultural e Roteirista | Los Angeles, EUA',
        image: '/autor.png'
    },
    social: {
        twitter: '@EntNeoStream',
        github: 'neostream',
        linkedin: 'entretenimento-neostream'
    },
    seo: {
        defaultTitle: 'Entretenimento',
        titleTemplate: '%s | Entretenimento',
        defaultDescription: 'Reviews de filmes e séries, resenhas de livros, análises de música e tudo sobre cultura pop. Seu portal completo de entretenimento.',
        keywords: [
            "filmes em cartaz hoje",
            "estreias de cinema 2025",
            "melhores filmes 2025",
            "filmes mais aguardados 2025",
            "trailer karatê kid lendas",
            "deadpool wolverine bilheteria",
            "invocação do mal 4 data",
            "animações família 2025",
            "sessões imax sp",
            "onde assistir os fantasmas ainda se divertem",
            "crítica divertidamente 2",
            "filmes marvel fase 6",
            "ingressos meia-entrada cinema",
            "festival de gramado programação",
            "filmes brasileiros premiados",
            "filme cult recomendação",
            "indicações oscar 2026",
            "pós-créditos universo dc",
            "cinema drive-in perto de mim",
            "pipoca gourmet cinema caseira",
            "séries nova temporada netflix",
            "lançamentos prime video 2025",
            "melhores séries disney plus",
            "demolidor renascido review",
            "round 6 temporada 2 estreia",
            "dramas coreanos populares 2025",
            "reality show bbb25 online",
            "quando ninguém nos vê sinopse",
            "assistir adolescência netflix",
            "top10 hbo max brasil hoje",
            "seriados clássicos remasterizados",
            "legenda pt-br rápida",
            "streaming 4k mais barato",
            "baixar episódios offline",
            "cancelamento assinatura streaming",
            "comparação catálogos brasil",
            "séries true crime em alta",
            "top séries adolescentes",
            "ranking audiência streaming 2025",
            "watch party como fazer",
            "top50 spotify brasil hoje",
            "hits do momento 2025",
            "músicas mais tocadas rádio",
            "lançamentos k-pop fevereiro",
            "festival the town line-up",
            "show taylor swift brasil setlist",
            "ingressos coldplay 2025",
            "trends trap nacional",
            "letras de funk 150 bpm",
            "remix eletrônica 2025",
            "mpb nova geração",
            "podcast música análise",
            "pré-save single spotify",
            "charts sertanejo universitário",
            "ranking billboard global",
            "clipe oficial vevo",
            "produtor musical contato",
            "sample royalty-free grátis",
            "música para reels viral",
            "playlist academia spotify",
            "jogos mais esperados 2025",
            "final fantasy vii rebirth pc",
            "spider-man 2 mods",
            "pré-venda gta 6 brasil",
            "citizen sleeper 2 gameplay",
            "consoles portáteis 2025",
            "xbox game pass novidades",
            "ps5 slim lançamento",
            "preço nintendo switch 2",
            "review freedom wars remaster",
            "crossplay como ativar",
            "metascore acima 90",
            "fps competitivo settings",
            "campeonatos valorant 2025",
            "skins raras fortnite loja",
            "cupom steam sale",
            "requisitos pc ultra 4k",
            "retro games coleção",
            "download indie grátis",
            "acessibilidade nos videogames",
            "calendário festivais brasil 2025",
            "rock in rio lineup completo",
            "joão rock ingressos",
            "coala festival atrações",
            "noronha weekend pacotes",
            "lollapalooza datas 2026",
            "camarote vip valores",
            "horário shows lives",
            "setlist ludmilla festival",
            "guia bloquinhos carnaval",
            "mapa comic con experience",
            "balada sertaneja hoje sp",
            "teatro musical são paulo",
            "ópera rio de janeiro",
            "stand-up comedy agenda",
            "aftermovie festival edição",
            "dicas camping festival",
            "melhores lugares arena",
            "meet & greet artistas",
            "merch oficial tour",
            "famosos mais seguidos instagram 2025",
            "fofoca do dia celebridades",
            "fotos paparazzi lollapalooza",
            "polêmica reality bbb25",
            "namoro de atores globais",
            "fortuna kim kardashian 2025",
            "celebridades bilionárias forbes",
            "influencers tiktok brasil top10",
            "briga no twitter artistas",
            "cancelamento cultura pop",
            "gravidez surpresa cantora",
            "casamento secreto famoso",
            "separação hollywood 2025",
            "looks tapete vermelho",
            "cirurgia plástica celebridade",
            "live solidária artistas",
            "roteiros carpool karaoke",
            "morte repentina ator",
            "comeback banda anos 2000",
            "trend corecore famosos",
            "universo star wars séries",
            "cronologia marvel explicada",
            "anime mais assistido crunchyroll",
            "cosplay dicas iniciantes",
            "mangá lançamento brasil",
            "colecionáveis funko promoção",
            "quadrinhos dc novidades",
            "dublagem brasileira história",
            "teoria stranger things final",
            "easter eggs pixar",
            "ranking melhores animes 2025",
            "card game pokémon torneio",
            "board games para família",
            "rpg de mesa gratuito",
            "live action one piece 2",
            "multiverso teorias",
            "fanfic crossover sucesso",
            "memes virais semana",
            "nostalgia anos 90 tv",
            "tour estúdios hollywood",
            "indicados grammy 2026",
            "vencedores globo de ouro",
            "premiação mtv miaw brasil",
            "emmy categorias drama",
            "ranking ibope novela",
            "recorde bilheteria abertura",
            "top ten box office usa",
            "oscar red carpet análise",
            "topseller bilheteria nacional",
            "golden joystick awards",
            "festival de cannes palme 2025",
            "troféu imprensa ganhadores",
            "prêmio multishow votações",
            "choice awards kids",
            "festival de veneza críticas",
            "número streams spotify recorde",
            "top trends tiktok awards",
            "categoria revelação latina",
            "melhores clipes vma",
            "audiência final bbb",
            "streaming com anúncios grátis",
            "inteligência artificial roteiros",
            "holograma show ao vivo",
            "cinema 4d motion chair",
            "lançamento óculos vr apple",
            "nft ingressos shows",
            "metaverso eventos musicais",
            "drones em espetáculos",
            "soundbar imersivo dolby atmos",
            "cinema sustentável energia",
            "projeção 8k doméstica",
            "games cloud streaming brasil",
            "algoritmos recomendação séries",
            "áudio espacial netflix",
            "5g concert experience",
            "avatars digitais celebridades",
            "deepfake em filmes",
            "pay-per-view on-demand",
            "bilheteria virtual tokenizada",
            "análise dados audiência em tempo real",
            "bilheteria recorde brasil 2025",
            "quanto ganha ator novela",
            "receitas disney 2025",
            "top10 animações bilheteria",
            "orçamento filme hollywood",
            "ranking streams primeira semana",
            "custo produção série",
            "salário cantor show",
            "merchandising filme lucro",
            "cinema nacional participação mercado",
            "pirataria impacto bilheteria",
            "reprise novela audiência",
            "bundle álbum merch",
            "recall produto filme",
            "documentário true crime sucesso",
            "musical broadway bilheteria",
            "exibição open air",
            "ingressos last minute desconto",
            "filme culto bilheteria tardia",
            "recorde trailer views 24h"
        ],
    },
    legal: {
        privacyPolicyUrl: '/politica-de-privacidade',
        termsOfServiceUrl: '/termos-de-uso',
        cookiePolicyUrl: '/politica-de-cookies',
        aboutUrl: '/sobre'
    }
} 