import type { SiteConfig } from '../site-config'

export const financasConfig: SiteConfig = {
    name: 'Finanças',
    description: 'Dicas práticas de finanças pessoais, investimentos e orçamento familiar',
    domain: 'financas.neostream.com.br',
    url: 'https://financas.neostream.com.br',
    logo: '/logo.png',
    favicon: '/favicon.ico',
    adsenseId: 'ca-pub-6189411019780384',
    themeColor: '#10b981',
    defaultLocale: 'pt-BR',
    author: {
        name: 'Omar Haddad',
        email: 'omar@neostream.com.br',
        url: 'https://financas.neostream.com.br/sobre',
        bio: 'Com carreira no setor bancário e startups financeiras, Omar escreve sobre economia, criptomoedas e educação financeira. Sua missão é ajudar leitores a entender e melhorar sua relação com o dinheiro.',
        credentials: 'Economista e Especialista em Fintech | Dubai, Emirados Árabes Unidos',
        image: '/autor.png'
    },
    social: {
        twitter: '@FinancasNeoStream',
        github: 'username/financas',
        linkedin: 'financas-neostream'
    },
    seo: {
        defaultTitle: 'Finanças',
        titleTemplate: '%s | Finanças',
        defaultDescription: 'Dicas práticas de finanças pessoais, investimentos inteligentes e orçamento familiar. Aprenda a economizar dinheiro, investir melhor e alcançar independência financeira.',
        keywords: [
            'como economizar dinheiro no dia a dia',
            'melhor app de controle financeiro 2025',
            'planilha de orçamento familiar grátis',
            'como investir dinheiro sem erro',
            'independência financeira antes dos 40',
            'melhores investimentos para iniciantes',
            'como sair das dívidas rápido',
            'dicas para montar fundo de emergência',
            'orçamento doméstico passo a passo',
            'controle de gastos mensais fácil',
            'melhor cartão de crédito sem anuidade',
            'como melhorar score de crédito',
            'como planejar aposentadoria cedo',
            'finanças pessoais para casais',
            'economizar em contas de luz e água',
            'aplicativos de finanças pessoais recomendados',
            'como poupar 20% do salário',
            'investimento em tesouro direto passo a passo',
            'como declarar imposto de renda simples',
            'dívida consolidada vale a pena',
            'fundos imobiliários melhores 2025',
            'como funciona a previdência privada',
            'comparativo entre bancos digitais e tradicionais',
            'crédito consignado vale a pena',
            'rendimento médio poupança atual',
            'como fazer portabilidade de empréstimo',
            'dicas de economia para família grande',
            'melhor cartão de crédito internacional',
            'investimento no exterior para brasileiros',
            'como usar cashback no dia a dia',
            'melhores corretoras brasileiras 2025',
            'começar a investir com pouco dinheiro',
            'como controlar gastos no cartão de crédito',
            'plano de previdência vs tesouro direto',
            'como investir em ações para iniciantes',
            'educação financeira para adolescentes',
            'como montar uma reserva de emergência',
            'investimento em criptomoedas seguro',
            'como fazer renda passiva mensal',
            'melhores investimentos com baixo risco',
            'simulador de financiamento imobiliário gratis',
            'comparativo de empréstimos pessoais 2025',
            'dicas de economia para aposentados',
            'como montar carteira de investimentos diversificada',
            'planejamento financeiro para autônomos',
            'como cancelar serviços desnecessários',
            'controle financeiro com Power BI',
            'dicas para renegociar dívidas com banco'
        ]
    },
    ymyl: {
        isYMYL: true,
        financialDisclaimer: 'As informações financeiras fornecidas neste site são apenas para fins educacionais e informativos. Não oferecemos consultoria financeira ou de investimentos. Sempre consulte um profissional financeiro qualificado antes de tomar decisões de investimento. Os investimentos envolvem riscos e podem resultar em perdas.'
    },
    legal: {
        privacyPolicyUrl: '/politica-de-privacidade',
        termsOfServiceUrl: '/termos-de-uso',
        cookiePolicyUrl: '/politica-de-cookies',
        aboutUrl: '/sobre'
    }
}