import type { SiteConfig } from '../site-config'

export const technewsConfig: SiteConfig = {
    name: 'Tech News',
    description: 'Últimas notícias e tendências em tecnologia, inovação e ciência',
    domain: 'tech-news.neostream.com.br',
    url: 'https://tech-news.neostream.com.br',
    logo: '/logo.png',
    favicon: '/favicon.ico',
    adsenseId: 'ca-pub-6189411019780384',
    themeColor: '#8b5cf6',
    defaultLocale: 'pt-BR',
    author: {
        name: 'Aisha Nakamura',
        email: 'aisha@neostream.com.br',
        url: 'https://tech-news.neostream.com.br/sobre',
        bio: 'Especialista em inteligência artificial e robótica, com mais de 10 anos de experiência no Vale do Silício e no Japão. Apaixonada por tecnologia acessível e ética digital, escreve sobre as inovações que estão moldando o futuro.',
        credentials: 'Engenheira de Software e Futurista | Tóquio, Japão',
        image: '/autor.png'
    },
    social: {
        twitter: '@TechNewsNeoStream',
        github: 'neostream',
        linkedin: 'tech-news-neostream'
    },
    seo: {
        defaultTitle: 'Tech News',
        titleTemplate: '%s | Tech News',
        defaultDescription: 'Últimas notícias e tendências em tecnologia, IA, startups e inovação. Análises aprofundadas do mundo tech e suas implicações para o futuro.',
        keywords: [
            // Desenvolvimento de Software
            "curso de programação gratuito",
            "como aprender lógica de programação",
            "github actions tutorial",
            "boas práticas clean code",
            "arquitetura hexagonal exemplos",
            "programação assíncrona javascript",
            "design patterns em go",
            "principio solid explicado",
            "testing tdd jest",
            "documentação api openapi",
            "ci cd com docker",
            "monorepo vs polyrepo",
            "graphql vs rest performance",
            "serverless lambdas aws",
            "microserviços comunicação event driven",
            "nestjs melhor prática",
            "framework express 2025",
            "nextjs 15 novidades",
            "react server components exemplo",
            "sveltekit vantagens",

            // Linguagens de Programação
            "python 3.13 features",
            "java 22 lts",
            "go generics exemplos",
            "rust ownership explicação",
            "typescript decorators uso",
            "kotlin coroutines avançado",
            "c sharp minimal api",
            "swiftui curso básico",
            "php 9 release",
            "dart null safety dicas",
            "scala functional programming",
            "ruby on rails 8",
            "elixir phoenix liveview",
            "haskell monads simples",
            "lua scripting games",
            "r linguagem estatística",
            "matlab vs python data science",
            "c++ modules performance",
            "objective c legado",
            "assembly otimização",

            // Inteligência Artificial & ML
            "tutorial tensorflow 3",
            "pytorch transformers pipeline",
            "fine tuning llm open source",
            "chatgpt api exemplos",
            "agentes autônomos langgraph",
            "mlops kubeflow pipeline",
            "modelos foundation open weight",
            "vector database chroma",
            "retrieval augmented generation rag",
            "autoencoder detecção anomalia",
            "machine learning interpretabilidade",
            "dados sintéticos privacidade",
            "reinforcement learning aplicações",
            "nlp classificação sentimentos",
            "visão computacional yolo v10",
            "edge ai inferência",
            "genai riscos éticos",
            "ai governance guidelines",
            "model cards documentação",
            "prompt engineering dicas",

            // Cloud Computing & DevOps
            "aws certificação solutions architect",
            "azure devops pipelines",
            "google cloud functions preço",
            "kubernetes cluster bare metal",
            "terraform módulos reutilizáveis",
            "iac melhores práticas",
            "observabilidade opentelemetry",
            "prometheus alertmanager guia",
            "ci cd gitlab saas",
            "argo cd vs flux",
            "docker compose v3",
            "finops otimizar custos cloud",
            "multi cloud strategy",
            "cloud híbrida openstack",
            "sre indicadores sli slo",
            "backup disaster recovery cloud",
            "edge computing casos uso",
            "api gateway comparativo",
            "service mesh istio tutorial",
            "k8s operador custom resource",

            // Cibersegurança
            "zero trust arquitetura",
            "fido2 autenticação senha",
            "segurança api owasp top10 2025",
            "devsecops pipeline",
            "criptografia pós quântica",
            "ransomware as a service",
            "phishing awareness treinamento",
            "pentest web checklist",
            "cve scanner automático",
            "endpoint detection response edr",
            "siem open source",
            "dast vs sast",
            "jwt vs oauth2 segurança",
            "double extortion ransomware",
            "segurança em contêineres",
            "vpn wireguard configuração",
            "cloudflare zero trust",
            "tokenização dados sensíveis",
            "gestão de identidade iam",
            "compliance lgpd tecnologia",

            // Dados, BI & Analytics
            "engenharia de dados carreira",
            "etl vs elt diferenças",
            "data lakehouse arquitetura",
            "apache spark structured streaming",
            "delta lake unity catalog",
            "bigquery custos otimização",
            "pipeline airflow exemplos",
            "dbt incremental model",
            "power bi dashboards interativos",
            "metabase vs superset",
            "databricks servidorless",
            "kafka Streams processamento evento",
            "clickhouse alta performance",
            "presto trino consultas",
            "governança de dados catálogo",
            "data mesh princípios",
            "quality great expectations",
            "analytics em tempo real",
            "engenheiro ml vs data scientist",
            "certificação data engineer",

            // Blockchain, Cripto & Web3
            "smart contract solidity 0.9",
            "erc 4337 account abstraction",
            "layer2 rollups arbritrum",
            "staking ethereum guia",
            "defi protocolos populares",
            "nft utilidade real",
            "wallet hardware ledger nano",
            "dapp react web3js",
            "crypto compliance regulacao brasil",
            "tokenomics fundamentos",
            "dao governança descentralizada",
            "oráculos chainlink uso",
            "did identidade digital",
            "hyperledger fabric exemplos",
            "blockchain híbrida casos",
            "cbdc banco central",
            "sidetree did method",
            "airdrops segurança",
            "zk snarks explicação",
            "bridge cross chain",

            // IoT, Hardware & Edge
            "arduino projetos iniciante",
            "raspberry pi 6 specs",
            "esp32 wifi bluetooth",
            "iot mqtt protocolo",
            "sensores lora wan",
            "edge ai nvidia jetson",
            "home assistant automação",
            "firmware ota update",
            "digital twin indústria 4.0",
            "5g iot cases",
            "protocolos opc ua",
            "smart factory brasil",
            "microcontrolador risc v",
            "hardware open source",
            "iot security best practices",
            "inteligência de energia solar iot",
            "wearables saúde dados",
            "beacons bluetooth marketing",
            "agricultura de precisão sensores",
            "drone mapeamento 3d",

            // Mobile & UX/UI
            "react native 0.75",
            "flutter 4 features",
            "kotlin multiplatform mobile",
            "swiftui animated list",
            "design system figma tokens",
            "ux research remoto",
            "acessibilidade wcag 3",
            "dark mode nativo",
            "animation framer motion",
            "performance lighthouse mobile",
            "pwa instalação android",
            "gestos react native",
            "apple vision os design",
            "haptics feedback ux",
            "designer vs dev colaboração",
            "usabilidadetest remoto",
            "material you guidelines",
            "microinterações mobile",
            "responsive grid css",
            "scroll snapping css",

            // Gestão de Produto & Agile
            "roadmap produto templates",
            "metrics north star",
            "lean startup pivot",
            "okrs engenharia de software",
            "scrum vs kanban híbrido",
            "priorização rices score",
            "product discovery técnicas",
            "design sprint passo a passo",
            "customer journey mapping",
            "growth hacking experimentos",
            "churn análise saas",
            "retenção de usuários app",
            "pricing baseado em valor",
            "feature flag rollouts",
            "a11y como diferencial produto",
            "documentação readme driven",
            "plataforma de pagamentos api",
            "experimentos ab testing",
            "blue green deploy",
            "squad multidisciplinar",

            // Metaverso, XR & Games
            "unity 2025 road map",
            "unreal engine 6 features",
            "webxr tutorial",
            "oculus quest 4 specs",
            "metaverso corporativo cases",
            "vr treinamento industrial",
            "ar kit reconhecimento rosto",
            "hand tracking sdk",
            "occlusion ar exemplo",
            "gamificação aplicativos saúde",
            "play to earn jogos",
            "digital assets interoperáveis",
            "cloud gaming latency",
            "on device rendering",
            "3d modeling blender curso",
            "shader graph iniciantes",
            "procedural generation unity",
            "ray tracing tempo real",
            "game design document",
            "monetização jogos mobile"
        ],
    },
    legal: {
        privacyPolicyUrl: '/politica-de-privacidade',
        termsOfServiceUrl: '/termos-de-uso',
        cookiePolicyUrl: '/politica-de-cookies',
        aboutUrl: '/sobre'
    }
}