import type { SiteConfig } from '../site-config'

export const viagemlifestyleConfig: SiteConfig = {
    name: 'Viagem e lifestyle',
    description: 'Dicas e inspirações de viagens, lifestyle e bem-estar: roteiros exclusivos, luxo acessível, experiências saudáveis e tendências em turismo para quem busca viver melhor.',
    domain: 'viagem-lifestyle.neostream.com.br', // TODO: Substitua pelo seu domínio
    url: 'https://viagem-lifestyle.neostream.com.br', // TODO: Substitua pela sua URL
    logo: '/logo.png',
    favicon: '/favicon.ico',
    adsenseId: 'ca-pub-6189411019780384', // TODO: Substitua pelo seu ID do AdSense
    themeColor: '#3b82f6', // blue-500
    defaultLocale: 'pt-BR',
    author: {
        name: 'Camila Duarte',
        email: 'camila@neostream.com.br',
        url: 'https://viagem-lifestyle.neostream.com.br/sobre',
        bio: 'Camila trocou uma carreira corporativa por uma mochila e nunca mais parou. Latina, LGBTQIA+, e apaixonada por culturas locais, compartilha roteiros, experiências autênticas e dicas práticas para viajantes curiosos.',
        credentials: 'Jornalista e Nômade Digital | Lisboa, Portugal',
        image: '/autor.png'
    },
    social: {
        twitter: '@viagem-lifestyle', // TODO: Substitua pelo seu Twitter
        github: 'username/viagem-lifestyle', // TODO: Substitua pelo seu GitHub
        linkedin: 'company/viagem-lifestyle' // TODO: Substitua pelo seu LinkedIn
    },
    seo: {
        defaultTitle: 'Viagem e lifestyle',
        titleTemplate: '%s | Viagem e lifestyle',
        defaultDescription: 'Dicas e inspirações de viagens, lifestyle e bem-estar: roteiros exclusivos, luxo acessível, experiências saudáveis e tendências em turismo para quem busca viver melhor.',
        keywords: [
            // Destinos brasileiros em alta
            "barra de tabatinga rn",
            "camaçari bahia praias",
            "córrego do bom jesus mg",
            "passo de camaragibe alagoas",
            "florianópolis 2025 verão",
            "brasília turismo cultural",
            "campos do jordão inverno 2025",
            "olímpia parque aquático",
            "mairiporã ecoturismo",
            "chapada dos veadeiros trilhas",
            "jalapão aventura",
            "gramado natal luz 2025",
            "lençóis maranhenses roteiro",
            "bonito ms mergulho",
            "ferrugem sc surf",
            "paraty centro histórico",
            "alter do chão praia de rio",
            "serra gaúcha vinhos",
            "praia do rosa baleias",
            "ilhabela trilhas cachoeira",

            // Destinos internacionais tendência
            "tóquio cerejeiras 2025",
            "cartagena colombia centro histórico",
            "puerto escondido surf",
            "tromsø noruega aurora boreal",
            "san pedro de atacama deserto",
            "bali indonésia workation",
            "lisboa portugal nômade digital",
            "barcelona gastronomia michelin",
            "dubai expo city 2025",
            "queenstown nova zelândia aventura",
            "curaçao praias caribe",
            "banff canadá parque nacional",
            "valle sagrado peru trilha",
            "amalfi itália costa ensueño",
            "kruger áfrica safári",
            "vancouver ciclismo urbano",
            "berlim arte urbana",
            "budapeste banhos termais",
            "istanbul cultural mix",
            "marrakesh souks coloridos",

            // Tipos de viagem & tendências
            "ecoturismo brasil 2025",
            "slow travel significado",
            "workation destinos baratos",
            "digital nomad visa requisitos",
            "viagem pet friendly",
            "turismo gastronômico rotas",
            "viagem de experiência imersiva",
            "volunturismo américa latina",
            "turismo regenerativo",
            "luxury camping glamping",
            "road trip rota 66 brasil",
            "viagem solo feminina",
            "viagem acessível cadeirante",
            "cicloturismo litoral",
            "motorhome pelo brasil",
            "cruzeiro temático wellness",
            "retiro de yoga floresta",
            "longevity retreat europa",
            "viagem sustentável compensar carbono",
            "turismo de aventura rapel",

            // Planejamento & economia
            "passagens aéreas baratas",
            "alerta de preço passagem",
            "melhor época para viajar",
            "seguro viagem internacional",
            "câmbio turismo hoje",
            "documentos para passaporte",
            "check list viagem internacional",
            "vacinas obrigatórias viagem",
            "mochila viagem minimalista",
            "malas 23kg medidas",
            "roteiro 7 dias europa",
            "roteiro 15 dias ásia",
            "cartão multimoeda travel money",
            "como acumular milhas rápido",
            "programa de fidelidade análise",
            "aluguel de carro comparativo",
            "apps viagem offline",
            "orçamento viagem planilha",
            "chip internacional dados ilimitados",
            "tax free compras europa",

            // Hospedagem & acomodações
            "airbnb dicas segurança",
            "hotel boutique brasil",
            "hostel trabalho voluntário",
            "resort all inclusive caribe",
            "couchsurfing como funciona",
            "casa container hospedagem",
            "pousada pet friendly serra",
            "hotel fazenda família",
            "cabana de vidro montanha",
            "eco lodge amazônia",
            "hotel cápsula japão",
            "villa de luxo toscana",
            "hotéis com coworking",
            "hotel sustentável selva",
            "resort para crianças",
            "hospedagem barata europa",
            "camping com estrutura",
            "fazenda vegana estadia",
            "hotel flutuante noruega",
            "pousada romântica litoral",

            // Transporte & mobilidade
            "voo low cost europa",
            "trem bala japão jr pass",
            "interrail pass europa",
            "ônibus leito brasil",
            "bicicleta compartilhada cidade",
            "patinete elétrico viagem",
            "aplicativo táxi internacional",
            "cruzeiro fluvial europa",
            "motorhome aluguel chile",
            "carpool estrada brasil",
            "blablacar carona europa",
            "passagem de ferry grécia",
            "voo com milhas resgate",
            "classe executiva promo",
            "upgrade cabine aéreo",
            "bagagem despachada regras",
            "fast track aeroporto",
            "sala vip prioridade",
            "seguro franquia carro",
            "locomoção acessível uber assist",

            // Lifestyle – wellness & bem-estar
            "mindfulness viagem",
            "spa day resort",
            "banho de floresta japão",
            "trilha meditativa montanha",
            "alimentação saudável viagem",
            "academia hotel grátis",
            "rotina saudável on the road",
            "retiro detox digital",
            "termalismo wellness europa",
            "fluxo de circadiano jet lag",
            "bike and wine tour",
            "corrida de rua destinos",
            "longevity clinic suíça",
            "viagem ayurveda índia",
            "reiki retiro bali",
            "cruzeiro fitness",
            "hotel com aulas de yoga",
            "wellness coaching viagem",
            "turismo médico check up",
            "viagem antiestresse",

            // Lifestyle – casa & decoração
            "minimalismo decoração apartamento",
            "estilo hygge brasil",
            "japandi design interiores",
            "plantas em casa urban jungle",
            "home office ergonômico",
            "organização método konmari",
            "iluminação natural dicas",
            "móveis sustentáveis",
            "velas aromáticas relax",
            "cromoterapia quarto",
            "decoração boho chic",
            "paleta cores 2025 casa",
            "renovar ambientes low cost",
            "diy reciclagem móveis",
            "loft industrial ideias",
            "tapete kilim estilo",
            "parede verde vertical",
            "smart home dispositivos",
            "casa container projeto",
            "tiny house brasil",

            // Lifestyle – moda & beleza
            "armário cápsula feminino",
            "moda sustentável marcas brasileiras",
            "brechó online luxo",
            "upcycling roupas dicas",
            "tecido vegano alternativas couro",
            "skincare minimalista",
            "protetor solar reef safe",
            "beleza limpa clean beauty",
            "perfume sólido viagem",
            "penteado prático viagem",
            "cosmético zero waste",
            "maquiagem multifuncional",
            "roupas anti UV praia",
            "athleisure tendências 2025",
            "sapato barefoot conforto",
            "relógio smartwatch fitness",
            "óculos sol biodegradável",
            "biquíni reversível",
            "jaqueta impermeável leve",
            "malas inteligentes rastreáveis",

            // Lifestyle – hobbies & rotina
            "fotografia de viagem dicas",
            "blog de viagem monetizar",
            "vídeo vlogs equipamentos",
            "diário de gratidão",
            "aulas de culinária local",
            "idiomas aplicativos grátis",
            "meditação guiada app",
            "leitura kindle viagem",
            "podcasts viagens inspiradores",
            "café de especialidade em casa",
            "vinhos naturais tendência",
            "cervejaria artesanal tour",
            "jardinagem varanda pequena",
            "cicloturismo urbano",
            "corrida matinal ritual",
            "trabalho remoto balanceamento",
            "finanças pessoais viajante",
            "voluntariado local comunidade",
            "colecionar ímãs viagem",
            "planejamento semanal bullet journal"
        ]
    },
    legal: {
        privacyPolicyUrl: '/politica-de-privacidade',
        termsOfServiceUrl: '/termos-de-uso',
        cookiePolicyUrl: '/politica-de-cookies',
        aboutUrl: '/sobre'
    }
}